name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: 'generate report'
      run: |
        pip install coverage pytest pytest-cov
        pip install -e ".[dev]"
        pytest --cov --junitxml=junit.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
